# Generated by Django 4.2.7 on 2025-08-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        # Add status field
        migrations.AddField(
            model_name='invite',
            name='status',
            field=models.CharField(
                choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')],
                default='pending',
                max_length=10
            ),
        ),
        # Rename accepted_at to responded_at
        migrations.RenameField(
            model_name='invite',
            old_name='accepted_at',
            new_name='responded_at',
        ),
        # Remove unique constraint to allow re-invites after rejection
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together=set(),
        ),
    ]
