apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: todos-app
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/vpc-access-connector: projects/PROJECT_ID/locations/REGION/connectors/todos-connector
    spec:
      containerConcurrency: 80
      timeoutSeconds: 3600  # 1 hour for WebSocket connections
      containers:
      - image: gcr.io/PROJECT_ID/todos-app
        ports:
        - containerPort: 8080
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "todos_project.settings_prod"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: todos-secrets
              key: secret-key
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: todos-secrets
              key: db-name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: todos-secrets
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todos-secrets
              key: db-password
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: todos-secrets
              key: db-host
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: todos-secrets
              key: redis-host
        - name: GS_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: todos-secrets
              key: bucket-name
        - name: GOOGLE_OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: todos-secrets
              key: oauth-client-id
        - name: GOOGLE_OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: todos-secrets
              key: oauth-client-secret
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: todos-secrets
              key: openai-api-key
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 256Mi
      serviceAccountName: todos-service-account