version: '3.8'

services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 todos_project.asgi:application
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgres://todos_user:todos_password@db:5432/todos_db
      - REDIS_URL=redis://redis:6379/0
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SITE_DOMAIN=${SITE_DOMAIN}
    volumes:
      - static_volume:/app/staticfiles
    restart: unless-stopped
    depends_on:
      - db
      - redis

  db:
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    restart: unless-stopped
    volumes:
      - redis_data:/data

  celery:
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  static_volume: