version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: todos_db
      POSTGRES_USER: todos_user
      POSTGRES_PASSWORD: todos_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 todos_project.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://todos_user:todos_password@db:5432/todos_db
      - REDIS_URL=redis://redis:6379/0
      - DEBUG=1

  celery:
    build: .
    command: celery -A todos_project worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://todos_user:todos_password@db:5432/todos_db
      - REDIS_URL=redis://redis:6379/0

volumes:
  postgres_data: