# Generated by Django 4.2.7 on 2025-08-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_time',
            field=models.CharField(blank=True, help_text='Estimated time', max_length=200, null=True),
        ),
    ]
