# Generated by Django 4.2.7 on 2025-08-20 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_estimated_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='ai_estimated_time',
        ),
    ]
